### ISSUE TITLE
confli push niveau

### ISSUE THREAD

**Issue by PatrycjaDrew** [dudleydehenau/ScapeGame#4]
Lorsque je veux push ce que j'ai fais dans le code, le niveau chateau, ça ne veux pas le faire car d'autres personnes ont push pendant que je travaillais dans le projet

**Comment by dudleydehenau** [comment]
J'ai merger les fonctionnalités du commit https://github.com/dudleydehenau/ScapeGame/commit/ad21a3fccc80aa6bec9e5b6fbea7ad171b4635cf avec la branche PatConflit020424 et l'ai push dans Dev. Fin de l'issue
