### ISSUE TITLE
OLD DDL de la base de donnée

### ISSUE THREAD

**Issue by dudleydehenau** [dudleydehenau/ScapeGame#5]
Je souhaite, à des fin de productivité, avoir accès à la base de donnée au à l'ancien DDL de la base de donnée. J'en ai besoin pour pouvoir travailler sur l'hébergement et d'autre vont en avoir besoin dans la semaine
@maxcorte

**Comment by maxcorte** [comment]
Voilà j'ai push.
tu peux essayé et revenir vers mo si il y a un problème :)
